"""
Customer lifetime value (LTV) by cohort.
 
Builds a cumulative LTV-per-customer heatmap (based on margin) for each
acquisition cohort from eda06_customers02, showing how much margin an
average customer in a given cohort has generated by month N of their
lifecycle.
 
If customers_df is not passed in (script run standalone) — computes it via
eda06_customers02.main(). If passed in (called from an orchestrator like
main.py) — uses it directly, without recomputing the previous stage.
"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from eda06_customers02 import main as eda06_customers02_main
from eda01_intro import print_section

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)


def main(
    df: pd.DataFrame | None = None,
    verbose: bool = True,
) -> pd.DataFrame:
    if df is None:
        df = eda06_customers02_main(verbose=False)

    cohort_sizes = (
        df[df["cohort_index"] == 0]
        .groupby(by=["cohort_month"])["customer_id"]
        .nunique()
    )

    cohort_grouped = (
        df.groupby(by=["cohort_month", "cohort_index"])["margin"]
        .sum()
        .reset_index()
    )
    margin_matrix_raw = cohort_grouped.pivot(
        index="cohort_month", columns="cohort_index", values="margin"
    )

    ######################################################
    # MASK OUT COHORT-INDEX CELLS THE COHORT HASN'T REACHED YET
    ######################################################
    # margin_matrix_raw is NaN both where a cohort had zero margin in a
    # month it had already reached (legitimate 0) AND where the cohort
    # simply hasn't existed long enough yet relative to the most recent
    # order_month in the data (should stay NaN, not be treated as 0).
    # Naively filling all NaN with 0 before cumsum() would let young
    # cohorts' LTV curves flatten and silently "predict" future months
    # that haven't happened. We compute each cohort's actual maximum
    # observed age and mask cumulative LTV back to NaN beyond it.
    max_order_month = df["order_month"].max()
    max_observed_age = {
        cohort_month: (
            (max_order_month.year - cohort_month.year) * 12
            + (max_order_month.month - cohort_month.month)
        )
        for cohort_month in margin_matrix_raw.index
    }
    valid_age_mask = pd.DataFrame(
        {
            col: margin_matrix_raw.index.map(
                lambda cm: col <= max_observed_age[cm]
            )
            for col in margin_matrix_raw.columns
        },
        index=margin_matrix_raw.index,
    )

    margin_matrix = margin_matrix_raw.fillna(0)
    cumulative_margin = margin_matrix.cumsum(axis=1).where(valid_age_mask)
    ltv_matrix = cumulative_margin.divide(cohort_sizes, axis=0)

    if verbose:

        print_section("LTV MATRIX", width=230)
        print(ltv_matrix.round(1))

        plt.figure(figsize=(13, 8))
        plt.title(
            "Cumulative LTV per Customer by Cohorts (Based on Margin)",
            fontsize=16,
            pad=20,
        )
        sns.heatmap(
            data=ltv_matrix,
            annot=True,
            fmt=".0f",
            cmap="YlGnBu",
            cbar_kws={"label": "LTV Value ($)"},
        )
        plt.ylabel("Cohort Birth Month", fontsize=12)
        plt.xlabel("Cohort Age (Months)", fontsize=12)
        plt.tight_layout()
        plt.show()

    return df


if __name__ == "__main__":
    df = main()

print()
